// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CalEvent struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Mutation struct {
}

type NewCalEvent struct {
	Name string `json:"name"`
}

type Query struct {
}
