// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

type Event struct {
	ID    string    `json:"id"`
	Title string    `json:"title"`
	User  uuid.UUID `json:"user"`
	Date  string    `json:"date"`
}

type Mutation struct {
}

type Query struct {
}

type NewEvent struct {
	Title string `json:"title"`
	Date  string `json:"date"`
}

type Range struct {
	Start string `json:"start"`
	End   string `json:"end"`
}
