name: frontend pipeline

on:
  push:
    paths:
      - frontend/**

jobs:
  lint:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: frontend
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - name: Install dependencies
      run: bun install --frozen-lockfile
    - name: Check style
      run: bun run lint

  build:
    needs: [lint]
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            eeritvan/calendar-frontend:${{ github.sha }}
            eeritvan/calendar-frontend:latest
          cache-from: type=registry,ref=eeritvan/calendar-frontend:buildcache
          cache-to: type=registry,ref=eeritvan/calendar-frontend:buildcache,mode=max
          outputs: type=docker,dest=${{ runner.temp }}/calendar-frontend-image.tar
      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: calendar-frontend-image
          path: ${{ runner.temp }}/calendar-frontend-image.tar